title: Ludewiki's Homepage
page-top-title: Yifan Dong
top-section-bg-text: Computer Science
home-subtitle: Yifan Dong Li&ensp;|&ensp董一凡;
copyright-text: '&copy; YiFan Dong 2025~. All Rights Reserved.'
