title: Ludewiki's Homepage
page-top-title: Yifan Dong
top-section-bg-text: Computer Science
home-subtitle: Yifan Dong &ensp;|董一凡 &ensp;
copyright-text: '&copy; YiFan Dong 2025~. All Rights Reserved.'
